language: ruby
services:
- postgresql
script:
- bundle exec rake db:{create,migrate}
- bundle exec rspec
deploy:
  api_key:
    secure: OSq1x18813ZNFiLR3MvLRgbgQgPhRnp/462q824rj6IW9IcvOo+C4hhQ3drmbAT+jADI5/OJ9gv04jJY6vC4y4l1mWmj9+OP2E82MTJ/W9Fo3u4dX3uGyNB+766puLMJS2lKCDxuiODNmdrE0TXuBpjTo6CGg/F6t9/eaW5EaxhJy0lRcKekK+rXufKsJ+ntCsxbiV8CvxbYJBmsM85qYvPUvg+v/x4VrsA7sKrAsCMAKFQXJd1EWEkXw/y8wCZAGPOZDiYDU7Z5iPpsQ0L0BJLtkJt14yVNBBduU6dj/qRryr4tE8SonX6TdE3QJ3AwdgHgSKj8KAHyRfUBM3TcZguI9wIgDzEecM/66JxXSkNckdjIbVUVSNfYEqGbtsDtiMlWP0cEAYmAV96XLuHS/TWU767SxPRPtAiRjZuZWkAoXB5H/hrL78RMVWrZTEImh4bPTGMPzhLck7qK45Um6N31y4dY1k1SdQbbz9zjmaSJLwsNhDDUTfQGaiwddGB+RJvmX3MYfqZl6C0STk6waLT8nv9oFkpb55eYRZahWEJTRrXYBmvUD+Kim27rT3yWwqUqVFk15OBMNmgd2Gb8Pj2atDNWc043Ts8rJUFwLBAtjRhx9Hk7guvg4f1fOkc9rbOxg2MDEOy3Tv9dO9UC8Ni/NRwrWLuxjy3xhLcIEto=
  app: sweater-weather-2003
  on:
    repo: melatran/sweater_weather
