language: ruby
cache: bundler
rbenv:
- 2.5.3
before_install:
- gem install bundler
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: CkT9n0oAMCqDsIKwmOGGik2rrp35xEmfz8cuYkRPmYqEnx4S7Umsubp4LW1QUoiGU7ekyWSm24N8tjCC68P3m9iyxh0xp/Zbbug1mUB05CrhWJXYN3QXzAiCFzXcsD1ka4sHeGdL2yobod3Nn3bbCZ0HTfR5S7nCy3AIRAqmWT981Xh2tkKIHZmDs2WEJWxEnMnHNSwBsrfs0O1VNVJrLUnO9OloAc/R+EQkSlgO5mcbrvwlCt5u5di3092Vyd/B1vHIzVkHNZ9cHjZ4fwJGvAT1RNUpUVZHIDAc5YM6yTcBl5yT1/Gd5gJukeZrllEs4o2ccPWW8Vd6aMX7Wzfw42Nmf6jKldFFBy5S7VNMUkrN2/azWY+xyBOu9hq912fcp7m9nKhBdLOxvGCDUZCiUTdzhZMdDAnZNTLj/GOk4RJ3B0GsAZjLHcAoxHNoViwCVm4MFbJxq+ZAz6TNNaIAKliSiTRbuUFrsHqnj8Hk1RcZoSyxlScjPmrMnpqBxKXeKdNWVOOAxi4y+TGty4O2Qtve44RgyR5qEKH1tLCWxyXgcBKFq8rsJ/c8Tdq3EpbTQrknisHeZ8iLptjl+9SaTo5xwFNJl6i89EQYaf00WN2fG0gsAWqbqsQxHSGpdZRUAXPFiUhf3fCaLrpUgkVVpjKh1VAuehIbrbjJ7Kd3jrY=
  app: sweater-weather-2003
  on:
    repo: melatran/sweater_weather
  run: rails db:migrate
  skip_cleanup: true
