language: ruby
cache: bundler
rbenv:
- 2.5.3
before_install:
- gem install bundler
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: lxTCnhyeccvEKPVjBPvx60FWH9B+zgY3ywHoVR86/R7BEPF82Z4wP4H4JAfhRJOtEkAplFQKslbREAH8tghql4sOsdZqzDxeWFks2Uy8voPQ0BtoT36NQVmMSTWKUFPjOYTU0xCky0zkaK9YeXHDTZsvjOCTJLbR+8eLzcSe7pOtVIL2MMO/wfaDRtWXq5b3OkOChOY8B6mVJnIDS0tKEGpXivnawE/iPW4ugNDQUmeYOvQNnQxThPzuiXp+OPs0NResdNrSfkI205U8bPKGMrEkpGHZQZk2EKKnmCzv6wLnoYj0voHP0ut8ZjVYoMICr7gCtbnkoCnNhlNMKl6j4uZTuYdN9PhiIR3izZYbnMAmeP0CrkwPByIfgv03jvifHSmuqc3xPCl+ZkoagcIRzq2mnOhcHv++KcNEDuMbsAlggLq+i5QAbqln6KPYio19SIO960X8pWcdRcEhi7Eb6AbaVuFoGDTeS+HmqOg/YDcC+ITP/pTEj5kWvsK7MfldHYwOUJWYQ4oEikJIuNaPCqr2znvK9gZoA6vdspf8TANARHHKbFqbgTTbl+kxrevX6nZPQPRiFpkbJOzFBlMXBQVDkKc7XPhpyYhtcBs69vOchQ0TpnZO9oVfG5xI5LpDGoscugMleZUeZ5c5NXPq7bOLHpHIlbVWiTkZgE+f/7s=
  app: sweater-weather-2003
  on:
    repo: melatran/sweater_weather
  run: rails db:migrate
